name: Gatya
main: Deceitya\Gatya\Main
version: 1.0.0
api: 4.0.0
load: POSTWORLD
author: deceitya
description: ガチャプラグイン
website: https://github.com/deceitya/Gatya
depend:
  - EconomyAPI
permissions:
  gatya.command.gt:
    default: true